Debian pull from upstream 2.4.7-1+4

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,41 +1,74 @@
 #!/usr/bin/make -f
-SHELL+= -e
+# -*- mode: makefile; coding: utf-8 -*-
 
-BUILD_UDEB := 1
+# Uncomment this to turn on verbose mode.
+#export DH_VERBOSE=1
 
+# Activate full hardening build flags
+export DEB_BUILD_MAINT_OPTIONS := hardening=+all
 
+## http://wiki.debian.org/onlyjob/get-orig-source
+PKD  = $(abspath $(dir $(MAKEFILE_LIST)))
+PKG  = $(shell dpkg-parsechangelog -l$(PKD)/changelog --show-field=Source)
+VER ?= $(shell dpkg-parsechangelog -l$(PKD)/changelog --show-field=Version | \
+	perl -ne 'print $$1 if m{^(?:\d+:)?(\d.*)(?:\-\d+.*)$$};')
+##
 
-D := $(CURDIR)/debian/ppp
+DIR_PPP := $(CURDIR)/debian/ppp
+DIR_PPP_DEV := $(CURDIR)/debian/ppp-dev
 
-# plugin ABI version, part of the directory name
-# shell expression from pppd/plugins/Makefile.linux
-PPPDDIR := $(shell awk -F '"' '/VERSION/ { print $$2; }' $(CURDIR)/pppd/patchlevel.h)
+TMP_PPP := $(CURDIR)/debian/tmp-ppp
+TMP_UDEB := $(CURDIR)/debian/tmp-udeb
 
+PPP_PLUGIN_ABI := $(shell awk -F '"' '/VERSION/ { print $$2; }' \
+	$(CURDIR)/pppd/patchlevel.h)
+VERSION_UPSTREAM := $(shell dpkg-parsechangelog -l$(PKD)/changelog \
+	--show-field=Version | \
+	perl -ne 'print $$1 if m{^(?:\d+:)?(\d.*)(?:\-\d+.*)$$};')
+VERSION_DEBIAN := $(shell dpkg-parsechangelog -l$(PKD)/changelog \
+	--show-field=Version | \
+	perl -ne 'print $$1 if m{^(?:\d+:)?(?:\d.*)\-(\d+.*)$$};')
+VERSION_ABI_PART := $(shell echo "$(VERSION_DEBIAN)" | \
+	perl -ne 'print $$1 if m{^(^\d+)\+};')
 
-ifdef BUILD_UDEB
-BUILD_UDEB_TARGET := .stamp-build-udeb
-else
-NO_PACKAGE := --no-package=ppp-udeb
-endif
-
-# Enable hardening build flags
-export DEB_BUILD_MAINT_OPTIONS = hardening=+all,-pie
-include /usr/share/dpkg/buildflags.mk
+UDEB_MAKEOPTS := \
+	CHAPMS= USE_CRYPT= NO_CRYPT_HACK=1 MPPE= \
+	FILTER= HAVE_MULTILINK= USE_TDB= \
+	HAS_SHADOW= USE_PAM= HAVE_INET6= \
+	CBCP= USE_SRP= MAXOCTETS= USE_BUILTIN_CRYPTO=1
+UDEB_PLUGIN_DIRS := pppoatm rp-pppoe
 
 ##############################################################################
-clean:
-	rm -rf .stamp-* pppd-udeb changelog-from-README
-	[ ! -f Makefile ] || $(MAKE) dist-clean
-	dh_clean
+%:
+	dh $@ --with systemd
 
-configure: .stamp-configure
-.stamp-configure:
+override_dh_testdir:
 	dh_testdir
-	./configure --prefix=/usr
-	touch $@
+	if [ "$(PPP_PLUGIN_ABI)" != "$(VERSION_UPSTREAM)" ]; then \
+	  echo; echo "**********"; \
+	  echo "VERSION in pppd/patchlevel.h must match upstream version."; \
+	  echo "Upstream version is '$(VERSION_UPSTREAM)'"; \
+	  echo "VERSION is '$(PPP_PLUGIN_ABI)'"; \
+	  echo "Aborting the build."; \
+	  echo "**********"; echo; \
+	  exit 1; \
+	fi
+	if [ -z "$(VERSION_ABI_PART)" ]; then \
+	  echo; echo "**********"; \
+	  echo "No ABI component found in the Debian revision field."; \
+	  echo "Please see debian/README.source for more information."; \
+	  echo "Aborting the build."; \
+	  echo "**********"; echo; \
+	  exit 1; \
+	fi
 
-udebdir: .stamp-udebdir
-.stamp-udebdir: .stamp-configure
+override_dh_auto_clean:
+	rm -rf pppd-udeb changelog-from-README $(TMP_PPP) $(TMP_UDEB) \
+		debian/extra/dh_ppp.1p
+	[ ! -f Makefile ] || $(MAKE) dist-clean
+
+override_dh_auto_configure:
+	./configure --prefix=/usr
 	if [ ! -d pppd-udeb/ ]; then \
 		mkdir pppd-udeb/ && \
 		cp -ldpR pppd/* pppd-udeb/; \
@@ -43,39 +76,8 @@ udebdir: .stamp-udebdir
 	cd pppd-udeb/ && make clean
 	cd pppd-udeb/plugins/ && make clean
 	perl -i -pe 's/ -DIPX_CHANGE\b//' pppd-udeb/Makefile
-	touch $@
 
-build-arch: build
-build-indep: build
-build: .stamp-build
-.stamp-build: .stamp-configure
-	dh_testdir
-	$(MAKE) COPTS="$(CFLAGS) $(CPPFLAGS)" LDOPTS="$(LDFLAGS)"
-	touch $@
-
-build-udeb: .stamp-build-udeb
-.stamp-build-udeb: .stamp-udebdir
-	dh_testdir
-	cd pppd-udeb/ && \
-	$(MAKE) COPTS="$(CFLAGS) $(CPPFLAGS) -Os -fomit-frame-pointer" \
-		LDOPTS="$(LDFLAGS)" \
-		CHAPMS= USE_CRYPT= NO_CRYPT_HACK=1 MPPE= \
-		FILTER= HAVE_MULTILINK= USE_TDB= \
-		HAS_SHADOW= USE_PAM= HAVE_INET6= \
-		CBCP= USE_SRP= MAXOCTETS= USE_BUILTIN_CRYPTO=1 \
-	&& \
-	cd plugins/ && \
-	$(MAKE) COPTS="$(CFLAGS) $(CPPFLAGS) -Os -fomit-frame-pointer" \
-		LDOPTS="$(LDFLAGS)" \
-		SUBDIRS='rp-pppoe pppoatm' PLUGINS=
-	touch $@
-
-install: .stamp-build $(BUILD_UDEB_TARGET) checkroot
-	dh_testdir
-	dh_clean -k
-	dh_installdirs
-	$(MAKE) install DESTDIR=$D/usr/
-
+changelog-from-README:
 	{ \
 	  sed -e "/^What's new in ppp-/,/^. New hooks have been added./!d" README ; \
 	  echo ; \
@@ -83,96 +85,81 @@ install: .stamp-build $(BUILD_UDEB_TARGET) checkroot
 	  cat Changes-2.3 ; \
 	} > changelog-from-README
 
-binary-arch: install
-	rm -rf $D/etc/ppp/*-secrets
-	mv $D/usr/include/ $D-dev/usr/
+override_dh_auto_build-arch: changelog-from-README
+	dh_auto_build -- \
+		COPTS="$(CFLAGS) $(CPPFLAGS)" LDOPTS="$(LDFLAGS)"
+	dh_auto_build -Dpppd-udeb/ -- \
+		COPTS="$(CFLAGS) $(CPPFLAGS) -Os -fomit-frame-pointer" \
+		LDOPTS="$(LDFLAGS)" \
+		$(UDEB_MAKEOPTS)
+	dh_auto_build -Dpppd-udeb/plugins -- \
+		COPTS="$(CFLAGS) $(CPPFLAGS) -Os -fomit-frame-pointer" \
+		LDOPTS="$(LDFLAGS)" \
+		SUBDIRS="$(UDEB_PLUGIN_DIRS)" PLUGINS=
 
-	install -m755 debian/extra/pon debian/extra/plog debian/extra/poff $D/usr/bin/
-	cp debian/extra/pon.completion $D/etc/bash_completion.d/pon
+override_dh_auto_build-indep: changelog-from-README
+	pod2man --section=1p --utf8 debian/extra/dh_ppp \
+		debian/extra/dh_ppp.1p
 
-	cp debian/extra/options $D/etc/ppp/
-	install -m755 debian/extra/ip-up debian/extra/ip-down debian/extra/ipv6-up debian/extra/ipv6-down \
-		$D/etc/ppp/
-	install -m755 debian/extra/0000usepeerdns-up $D/etc/ppp/ip-up.d/0000usepeerdns
-	install -m755 debian/extra/0000usepeerdns-down \
-		$D/etc/ppp/ip-down.d/0000usepeerdns
+override_dh_auto_install-arch:
+	dh_auto_install --destdir=$(TMP_PPP)/usr/
+	dh_auto_install -Dpppd-udeb/ --destdir=$(TMP_UDEB)/usr/ -- \
+		$(UDEB_MAKEOPTS)
 
-	install -m644 debian/extra/pap-secrets debian/extra/chap-secrets \
-		debian/extra/provider.peer debian/extra/provider.chatscript \
-		$D/usr/share/ppp/
-	install -m644 debian/extra/chatscript.pap $D/etc/chatscripts/pap
-	install -m644 debian/extra/chatscript.gprs $D/etc/chatscripts/gprs
+	for DIR in $(UDEB_PLUGIN_DIRS); do \
+		dh_auto_install -Dpppd-udeb/plugins/$$DIR \
+			--destdir=$(TMP_UDEB)/usr/; \
+	done
 
-	dh_installchangelogs -a changelog-from-README
-	dh_installdocs
-	dh_installexamples scripts/ debian/extra/autopppd debian/extra/userscripts-* \
-		debian/extra/popp debian/extra/filters debian/extra/options.ttyXX \
-		debian/extra/peers-* debian/extra/interfaces debian/extra/per-linkname
+override_dh_auto_install-indep:
+	$(MAKE) install-devel DESTDIR=$(DIR_PPP_DEV)/usr/
+	mkdir -p $(DIR_PPP_DEV)/usr/share/ppp-dev
+	$(PKD)/gen_substvars_dev $(VERSION_UPSTREAM) $(VERSION_ABI_PART) \
+	  > $(DIR_PPP_DEV)/usr/share/ppp-dev/substvars
+
+override_dh_installchangelogs:
+	dh_installchangelogs changelog-from-README
+
+override_dh_installexamples-arch:
+	dh_installexamples
+
 	# use our own version, not the upstream one
-	mv $D/usr/share/doc/ppp/examples/autopppd \
-		$D/usr/share/doc/ppp/examples/scripts/
-	dh_installman debian/extra/pon.1 debian/extra/pppoe-discovery.8
-	dh_link
-	dh_installlogrotate
-	dh_systemd_enable -pppp --name=pppd-dns
-	dh_installinit -pppp --name=pppd-dns --no-start
-	dh_systemd_start --no-start
-	dh_installpam
-	dh_lintian
+	mv $(DIR_PPP)/usr/share/doc/ppp/examples/autopppd \
+		$(DIR_PPP)/usr/share/doc/ppp/examples/scripts/
 
-ifdef BUILD_UDEB
-	grep '^[a-zA-Z0-9]' debian/extra/options | grep -v '^noipx' \
-		> $D-udeb/etc/ppp/options
-#	cp chat/chat $D-udeb/usr/sbin/
-	cp pppd-udeb/pppd $D-udeb/usr/sbin/
-	cp pppd-udeb/pppd pppd-udeb/plugins/rp-pppoe/pppoe-discovery \
-		$D-udeb/usr/sbin/
-	mkdir -p $D-udeb/usr/lib/pppd/$(PPPDDIR)/
-	cp pppd-udeb/plugins/rp-pppoe/rp-pppoe.so \
-		pppd-udeb/plugins/pppoatm/pppoatm.so \
-		$D-udeb/usr/lib/pppd/$(PPPDDIR)/
-	install -m755 debian/extra/ppp-udeb.ip-up $D-udeb/etc/ppp/ip-up
-	install -m755 debian/extra/ppp-udeb-postbaseinst \
-		$D-udeb/usr/lib/post-base-installer.d/30ppp
-	dh_installdebconf
-endif
+override_dh_systemd_enable:
+	dh_systemd_enable --name=pppd-dns
 
-	dh_strip		-a
-	dh_compress		-a
-	dh_fixperms		-a
+override_dh_installinit:
+	dh_installinit --name=pppd-dns --no-start
 
-	chown root:dip $D/usr/sbin/pppd \
-		$D/etc/ppp/ $D/etc/ppp/peers/ $D/etc/chatscripts/
-	chmod 4754 $D/usr/sbin/pppd
-	chmod 2750 $D/etc/ppp/peers/ $D/etc/chatscripts/
+override_dh_systemd_start:
+	dh_systemd_start --name=pppd-dns --no-start
 
-	dh_md5sums		-a
-	dh_shlibdeps		-a
-	dh_installdeb		-a
+override_dh_perl:
+	dh_perl -d --package=ppp-dev
+	dh_perl --no-package=ppp-dev
 
-	dh_gencontrol		-a $(NO_PACKAGE)
-	dh_builddeb		-a $(NO_PACKAGE)
+override_dh_fixperms-arch:
+	dh_fixperms
+	chown root:dip \
+		$(DIR_PPP)/etc/chatscripts/ \
+		$(DIR_PPP)/etc/ppp/ \
+		$(DIR_PPP)/etc/ppp/peers/ \
+		$(DIR_PPP)/usr/sbin/pppd
+	chmod 4754 $(DIR_PPP)/usr/sbin/pppd
+	chmod 2750 $(DIR_PPP)/etc/ppp/peers/ $(DIR_PPP)/etc/chatscripts/
 
-binary-indep: install
-	dh_installchangelogs	-i changelog-from-README
-	dh_installdocs		-i
+# Force dpkg-gensymbols to inspect pppd (it doesn't end .so) so that the
+# symbols file is generated. This needs the SONAME hack that gets applied in
+# debian/patches/pppd-soname-hack.patch to work. The -c2 below makes sure that
+# the build fails if there are any discrepancies in the symbols file in order
+# to catch ABI changes.
+override_dh_makeshlibs:
+	dh_makeshlibs --package=ppp -- -c2 -edebian/ppp/usr/sbin/pppd -V
+	dh_makeshlibs --no-package=ppp
 
-	dh_compress		-i
-	dh_fixperms		-i
-
-	dh_md5sums		-i
-	dh_installdeb		-i
-	dh_gencontrol		-i 
-	dh_builddeb		-i
-
-
-binary:	binary-arch binary-indep
-
-checkroot:
-	test root = "`whoami`"
-
-get-orig-source:
-	cd $(dir $(firstword $(MAKEFILE_LIST)))../ && \
-	uscan --rename --force-download --watchfile debian/watch --destdir $(CURDIR)
-
-.PHONY: binary binary-arch binary-indep unpack configure build clean checkroot
+## http://wiki.debian.org/onlyjob/get-orig-source
+get-orig-source: $(info I: $(PKG)_$(VER))
+	@echo "# Downloading..."
+	uscan --noconf --verbose --rename --destdir=$(CURDIR) --check-dirname-level=0 --force-download --download-version $(VER) $(PKD)
